In [8]:
import cppapi
import numpy as np

In [9]:
# create a test layer
neurons = 3
mse = cppapi.MeanSquareError()
test_layer = cppapi.TestWeightMultOp(mse, neurons)
X = np.random.randn(3, 2).astype(np.float32)
test_layer.forward(X)

In [10]:
print(test_layer.get_prediction().shape)

(3, 3)


In [11]:

target = np.random.randn(X.shape[0], neurons).astype(np.float32)
loss = test_layer.partial_train(X, target)

gradients = test_layer.get_gradients()

print(gradients)

[[-1.4384781   0.21798226]
 [ 1.2128748  -0.20140113]
 [ 0.15439644  0.24611461]]


In [12]:
linear_layer = cppapi.TestBiasOp(mse, neurons)
linear_layer.forward(X)
prediction = test_layer.get_prediction()

print(prediction.shape) # TODO check that this is actually the correct shape?
# I mean we have checks all throughout the operations but just not sure 
# if the order of operations changes things. 
print(X)
print(prediction)

(3, 3)
[[-0.47568557  0.34544384]
 [ 0.6538927   0.7076709 ]
 [ 0.83847576 -0.05836049]]
[[ 0.19358267 -0.43130675  0.3838737 ]
 [ 0.37567186  0.6561415   0.11067688]
 [-0.04243415  0.78969914 -0.37944388]]
