In [1]:
import cppapi
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import log_loss
from scipy.special import softmax


enc = OneHotEncoder(sparse_output=False)

X = np.random.randint(0, 3, (100, 1))

Xenc = enc.fit_transform(X)

print(Xenc)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0.

In [3]:
loss = cppapi.LossFn(cppapi.LossType.CROSS_ENTROPY)


Q = np.random.randn(100, 3)
print("Predictions:\n", Q)
print("Python softmax:\n", softmax(Q, axis=1))

cppapi.loss_functions.forward(loss, Q.astype(np.float32), Xenc.astype(np.float32))

print("softmax matrix\n", loss.place_holder)

print("cpp loss value:", loss.loss_value)

print(log_loss(Xenc, softmax(Q, axis=1)))

np.sum(-Xenc * np.log(loss.place_holder) - (1-Xenc) * np.log(1-loss.place_holder)) / 100


Predictions:
 [[ 2.11361574e+00 -5.20651457e-01  1.13158799e+00]
 [-7.11852843e-01 -6.96159166e-01 -1.04418480e+00]
 [-1.42335019e+00 -1.14918928e+00  1.42706748e+00]
 [-2.07537433e+00 -1.20757645e-01  4.77228568e-01]
 [ 7.95142200e-01  1.16132473e+00 -6.88275937e-01]
 [-1.17259432e+00 -1.76711540e-01  4.45576462e-01]
 [ 3.41234287e-01 -1.24090737e+00 -9.16517333e-02]
 [ 3.16199873e-01 -8.65069284e-01 -1.13689991e-01]
 [ 3.78606809e-01  1.11572113e+00  2.47736497e-03]
 [-1.24330204e+00 -1.06209375e+00 -2.13556896e-01]
 [-1.54471669e+00  3.45445528e-01  2.14732650e+00]
 [-2.75844574e-01  4.63273437e-01  3.23706961e-01]
 [-6.86345875e-01 -1.96636175e-01  1.35609869e+00]
 [ 5.47389940e-01  6.60194561e-01 -9.10600250e-01]
 [ 1.14726164e+00 -4.11671980e-01 -1.73249463e+00]
 [-1.04001789e+00 -1.47540431e+00  9.86490186e-01]
 [-3.25398263e-01 -1.17936707e+00 -4.26262104e-01]
 [-1.70261444e+00 -1.26679105e+00  2.62026433e+00]
 [-7.73884946e-01 -2.49537461e-01  8.21235238e-01]
 [ 1.12978765e+00

np.float64(2.438242892883718)